name: Pipeline con stages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar código
      uses: actions/checkout@v3

    - name: Build
      run: echo "Construyendo..."

    - name: Test
      run: echo "Ejecutando tests..."

    - name: Deploy
      run: echo "Desplegando..."
